# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='is_famous',
            field=models.BooleanField(default=0, verbose_name='是否经典'),
        ),
    ]
