# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-25 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20180825_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherinfo',
            old_name='iamge',
            new_name='image',
        ),
    ]
