# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-26 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20180825_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')], default='pxjg', max_length=10, verbose_name='机构类型'),
        ),
    ]
