# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_orginfo_is_famous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orginfo',
            name='is_famous',
        ),
    ]
